mkdir -p zoo1/{data,log}
mkdir -p zoo2/{data,log}
mkdir -p zoo3/{data,log}
mkdir -p bookie1/{data,log}
mkdir -p bookie2/{data,log}
mkdir -p bookie3/{data,log}
mkdir -p broker1/{data,log}
mkdir -p broker2/{data,log}
mkdir -p proxy/{data,log}
